package com.supergestao.Flyway.migration.assistant.dominio.mensagem;

public enum MensagemSistema {

    ATENCAO("Atenção!"),
    MENSAGEM_INFORMATIVA("Mensagem informativa"),
    CONFIRMACAO("Confirmação"),
    CONFIRMAR("Confirmar"),
    SAIR("Sair"),
    ERRO("Erro"),
    ALERTA("Alerta"),
    NOVA_FUNCAO("Nova Função"),
    NOVO_MODULO("Novo Módulo"),
    CADASTRAR_CONFIGURACAO("Cadastrar configurações"),
    SELECIONE_PASTA_ORIGEM("Selecione a pasta de origem"),
    CRIAR_MODULO("Deseja criar o módulo %s no diretorio %s?"),
    IR_CONFIGURACAO("Cadastrar configurações"),
    DESEJA_SALVAR_ALTERACAO("Deseja salvar as alterações?"),
    GRAVAR_REGEDIT("Não foi possível gravar no RegEdit do Windows"),
    EXISTE_MODULOS_CRIAR("Existe novos módulos a serem criados. Deseja criar agora?"),
    SALVAR_FUNCAO("Deseja criar a função %s no diretório: %s?"),
    LISTA_FUNCAO("Lista de funções."),
    LISTA_MODULO("Lista de módulos."),
    ERRO_SALVAR_REGISTRO("Erro ao salvar registro"),
    ERRO_CRIAR_ARVORE_MODULOS("Erro montar Arvore de Módulos/Funções."),
    ERRO_CRIAR_ARVORE_MODULOS_ARQUIVOS("Erro montar Arvore de Módulos/Funções com arquivos."),
    ERRO_CRIAR_ARVORE_ARQUIVOS("Não foi possível carregar os arquivo(s) do módulo: %s"),
    ARQUIVO_SALVO("Arquivo SQL salvo com sucesso!"),
    ALTERACAO_NAO_SALVA("Alterações não salvas"),
    DESCARTAR_ALTERACAO("O arquivo atual possui alterações não salvas. Deseja descartá-las para abrir o novo arquivo?"),
    CAMPO_OBRIGATORIO("O Campo %s tem preenchimento obrigatório."),
    VERIFIQUE_PREENCHIMENTO("Verifique o preenchimento dos campos obrigatórios."),
    FORMATO_DATA_INVALIDO("O Formato %s para data/hora é inválido."),
    FORMATO_DATA_NULL("Formato de data/hora não informado."),
    LOCALIDADE_DATA_INVALIDA("Localidade para data/hora não informada."),
    ARQUIVO_NAO_JAVA("O arquivo de entrada não é um arquivo .java. \\nVerifique o caminho do arquivo de entrada dos módulos, caminho usado: \\n%s"),
    ARQUIVO_JAVA("Selecione o arquivo .java com os módulos"),
    ERRO_PROCESSAR_ARQ_MODULO("Erro ao processar o arquivo de entrada dos módulos."),
    ERRO_PROCESSAR_MOD_EXISTENTE("Erro ao processar o módulos existente."),
    ERRO_SALVAR_MODULO("Erro ao salvar o módulo: %s"),
    ERRO_PROCESSAR_FUN_EXISTENTE("Erro ao processar as funções existentes."),
    ERRO_PROCESSAR_ARQ_EXISTENTE("Erro ao processar o arquivo migration: %s"),
    ERRO_ACESSAR_ARQ_EXISTENTE("Erro ao acessar os arquivos da função %s"),
    ERRO_SALVAR_FUNCAO("Erro ao salvar a função: %s"),
    ERRO_SALVAR_ARQUIVO("Erro ao salvar o arquivo: %s"),
    ERRO_OBTER_ACAO_BANCO("Erro ao converte Ação Banco: %s"),
    ERRO_CONVERTER_NOME_UNDO("Erro ao converte nome do arquivo Undo: %s"),
    ERRO_ARQUIVO_NAO_VERSIONED("O Arquivo não é do tipo Versioned Migration"),
    NAO_ARQUIVO_MIGRATION("O arquivo não é uma migration válida do Flyway!"),
    SCRIPT_VAZIO("O script SQL está completamente vazio e não tem efeito."),
    SCRIPT_NAO_PERMITIDO("No script SQL existe comandos não permitidos. %s"),
    SCRIPT_NAO_SEM_CONDICIONAL("No script SQL existe comandos que deveriam conter condicional. %s"),
    SCRIPT_ERRO_SINTAXE("O script SQL contem erro de sintaxe: %s"),
    SCRIPT_SEM_DICIONARIO("Ausência de Dicionário de Dados: Faltou a instrução 'COMMENT ON' para documentar a criação: %s"),
    SCRIPT_SEM_PADRAO_SQL("Não segue o padrão SQL: %s"),
    ERRO_ABERTURA_TELA("Erro ao tentar abrir a tela de: %s"),
    ERRO_GENERICO("Erro inesperado: %s"),
    ERRO_CSS("Erro ao carregar o arquivo CSS do editor SQL."),
    ERRO_LINHA_ERRO("Erro ao marcar o erro no editor SQL."),
    ERRO_PERL("Interpretador Perl não encontrado no PATH nem nos caminhos do Git.\\nInstale o Strawberry Perl (https://strawberryperl.com/) ou adicione o Perl do Git às variáveis de ambiente."),
    ERRO_RODAR_PGFORMATTER("Erro ao rodar pgFormatter local, código de saída:  %s: %s"),
    ERRO_IO_PGFORMATTER("Erro de E/S ao extrair ou rodar o pgFormatter, certifique-se de ter o Perl ou Git instalado: %s"),
    ERRO_INTERRUPCAO_PGFORMATTER("Processo do pgFormatter foi interrompido: %s"),
    ERRO_GERAL_PGFORMATTER("Falha geral ao formatar SQL localmente (certifique-se de que o Perl está no PATH): %s"),
    ERRO_INDENTAR_SQL("Falha ao indentar SQL"),
    SQL_VALIDADO("SQL validado com sucesso! Nenhum erro de sintaxe foi detectado."),
    FALHA_VALIDAR_SQL("Falha na validação do SQL: %s"),
    ERRO_LER_CLASS("Recurso não encontrado no classpath: %s"),
    ERRO_LINHA_SQL("Erro na linha: %s coluna: %s\nMensagem: %s"),
    SALVAR_ALTERACAO("Deseja salvar as alterações?"),
    CAMPO_DETALHES_VAZIO("O campo detalhes não pode ser vazio para o tipo de diálogo: %s"),
    ERRO_SALVAR_CONFIG("Erro ao salvar configurações"),
    ERRO_DECLARACAO_SEM_PONTO_VIRGULA("Erro na linha: %d coluna: %d \n Mensagem: Falta ponto e vírgula (;) ou erro de sintaxe na declaração de variáveis."),
    ERRO_DECLARACAO_ANTES_BEGIN("Erro na linha: %d coluna: %d \n Mensagem: Falta ponto e vírgula (;) na última declaração antes do 'BEGIN'."),
    ERRO_VARIAVEL_TRIGGER_INVALIDA("Erro na linha: %d coluna: %d \n Mensagem: Variável especial de trigger inválida ou incorreta: '%s'. Você quis dizer TG_OP ou TG_TABLE_NAME?"),
    ERRO_FUNCAO_SISTEMA_INCORRETA("Erro na linha: %d coluna: %d \n Mensagem: Função do sistema incorreta: '%s'. Você quis dizer %s?"),
    ERRO_ELSIF_FORA_IF("Erro na linha: %d coluna: %d \n Mensagem: Instrução 'ELSIF' fora de um bloco 'IF' aberto."),
    ERRO_THEN_SEM_IF("Erro na linha: %d coluna: %d \n Mensagem: Instrução 'THEN' sem correspondente 'IF' ou 'ELSIF'."),
    ERRO_THEN_INESPERADO("Erro na linha: %d coluna: %d \n Mensagem: Instrução 'THEN' inesperada nesta posição."),
    ERRO_SINTAXE_CONDICAO_CONTROLE("Erro na linha: %d coluna: %d \n Mensagem: Erro de sintaxe na condição do %s: %s"),
    ERRO_CONDICAO_CONTROLE("Erro na linha: %d coluna: %d \n Mensagem: Erro na condição do %s: %s"),
    ERRO_END_TOKEN_INESPERADO("Erro na linha: %d coluna: %d \n Mensagem: 'END' seguido por token inesperado: '%s'. Você quis dizer 'END IF', 'END LOOP' ou 'END CASE'?"),
    ERRO_ESTRUTURA_NAO_FECHADA("Erro na linha: %d coluna: %d \n Mensagem: A estrutura de controle '%s' iniciada nesta linha não foi fechada corretamente."),
    ERRO_IF_SEM_THEN("Erro na linha: %d coluna: %d \n Mensagem: Instrução 'IF' iniciada na linha %d, coluna %d não possui o 'THEN' correspondente."),
    ERRO_ELSIF_SEM_THEN("Erro na linha: %d coluna: %d \n Mensagem: Instrução 'ELSIF' iniciada na linha %d, coluna %d não possui o 'THEN' correspondente."),
    ERRO_END_SEM_ABERTURA("Erro na linha: %d coluna: %d \n Mensagem: Instrução 'END %s' sem correspondente '%s' aberto."),
    ERRO_END_FECHAMENTO_ERRADO("Erro na linha: %d coluna: %d \n Mensagem: Esperava fechar '%s' (iniciado na linha %d, coluna %d), mas tentou fechar '%s'."),
    ERRO_SINTAXE_CURSOR("Erro na linha: %d coluna: %d \n Mensagem: Erro de sintaxe no cursor '%s': %s"),
    ERRO_SQL_LINHA_COLUNA("Erro na linha: %d coluna: %d \n Mensagem: %s"),
    ERRO_PALAVRA_CHAVE_INCORRETA("Erro na linha: %d coluna: %d \n Mensagem: Palavra-chave incorreta: '%s'. Você quis dizer %s?"),
    ERRO_SINTAXE_ATRIBUICAO("Erro na linha: %d coluna: %d \n Mensagem: Erro de sintaxe na expressão da atribuição: %s"),
    ERRO_PALAVRA_CHAVE_PLPGSQL("Erro na linha: %d coluna: %d \n Mensagem: Palavra-chave PL/pgSQL incorreta: '%s'. Você quis dizer %s?"),
    ERRO_COMANDO_INVALIDO("Erro na linha: %d coluna: %d \n Mensagem: Comando ou palavra-chave inválida/desconhecida: '%s'."),
    ERRO_SINTAXE_CORPO("Erro na linha: %d coluna: %d \n Mensagem: Erro de sintaxe: %s"),
    ERRO_FALTA_PONTO_VIRGULA("Erro na linha: %d coluna: %d \n Mensagem: Falta ponto e vírgula (;) no final do comando"),
    CMD_DROP_DATABASE("DROP DATABASE"),
    CMD_DROP_CASCADE("DROP com CASCADE"),
    CMD_DROP_SCHEMA("DROP SCHEMA"),
    CMD_DROP_ROLE("DROP ROLE / DROP USER"),
    CMD_DROP_OWNED("DROP OWNED BY"),
    CMD_TRUNCATE("TRUNCATE TABLE"),
    CMD_ALTER_SYSTEM("ALTER SYSTEM"),
    CMD_ALTER_ROLE("ALTER ROLE / ALTER USER"),
    CMD_CREATE_EXTENSION("CREATE EXTENSION"),
    CMD_COPY("COPY"),
    CMD_DO_BLOCK("DO $$"),
    CMD_REVOKE("REVOKE"),
    CMD_GRANT("GRANT"),
    CMD_CREATE_ROLE("CREATE ROLE / CREATE USER"),
    CMD_SET_VARIABLE("SET de variável de sessão/configuração (SET search_path, SET role, etc.)"),
    CMD_RESET_VARIABLE("RESET de variável de configuração"),
    CMD_VACUUM("VACUUM / ANALYZE"),
    CMD_CLUSTER("CLUSTER"),
    CMD_REINDEX("REINDEX"),
    CMD_LOAD("LOAD"),
    CMD_LISTEN("LISTEN"),
    CMD_NOTIFY("NOTIFY"),
    CMD_SAVEPOINT("SAVEPOINT"),
    CMD_RELEASE_SAVEPOINT("RELEASE SAVEPOINT"),
    CMD_TRANSACTION("Comandos de transação (BEGIN/COMMIT/ROLLBACK)"),
    CMD_LOCK_TABLE("LOCK TABLE"),
    CMD_SECURITY_DEFINER("SECURITY DEFINER não permitido"),
    CMD_CREATE_LANGUAGE("CREATE LANGUAGE"),
    ERRO_UPDATE_SEM_WHERE("UPDATE sem WHERE detectado."),
    ERRO_UPDATE_WHERE_GENERICO("UPDATE com condição genérica (1=1) detectado."),
    ERRO_DELETE_SEM_WHERE("DELETE sem WHERE detectado."),
    ERRO_DELETE_WHERE_GENERICO("DELETE com condição genérica (1=1) detectado."),
    ERRO_INSERT_INVALIDO("INSERT inválido ou incompleto"),
    ERRO_INSERT_SEM_COLUNAS("INSERT sem lista de colunas explícita. Use: INSERT INTO tabela (col1, col2) VALUES (...)"),
    ERRO_SELECT_INTO("SELECT INTO não é permitido. Use CREATE TABLE AS SELECT para criar tabelas explicitamente."),
    ERRO_TABELA_SEM_PK("Tabela criada sem PRIMARY KEY"),
    ERRO_ELEMENTO_SEM_COMENTARIO("O elemento (%s) foi criado mas não possui comentário!"),
    ERRO_INDEX_SEM_NOME("Index sem nome definido"),
    ERRO_ALTER_TABLE_SEM_TABELA("ALTER TABLE sem identificação da tabela"),
    ERRO_FUNCTION_SEM_NOME("Function sem nome"),
    ERRO_NOMENCLATURA_SNAKE_CASE("%s \"%s\" não segue o padrão snake_case obrigatório. Use apenas letras minúsculas, números e underscore, começando com letra."),
    ERRO_TAMANHO_NOME_EXCEDIDO("%s \"%s\" ultrapassa 63 caracteres (limite do PostgreSQL). Nomes maiores são truncados silenciosamente pelo banco."),
    FUNTION_TRIGGER_ARG("Cabeçalho Function trigger com argumentos."),
    SELECIONE("Selecione um(a) %s"),
    SELECIONE_UNDO("Selecione o arquivo de origem Undo");

    private final String mensagem;

    MensagemSistema(String mensagem) {
        this.mensagem = mensagem;
    }

    public String getMensagem() {
        return mensagem;
    }

    public String MensagemComParametro(Object... parametros) {
        return String.format(this.mensagem, parametros);
    }
}
