package com.supergestao.Flyway.migration.assistant.dominio.tipo;

import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;

public enum PalavraChaveSql {
    // ==========================================
    // 1. COMANDOS DML E ESTRUTURA DE CONSULTAS
    // ==========================================
    SELECT("SELECT", "Inicia uma consulta para recuperar dados de uma ou mais tabelas."),
    FROM("FROM", "Especifica a tabela ou tabelas de origem em uma consulta."),
    WHERE("WHERE", "Filtra os registros de uma consulta com base em condições lógicas."),
    INSERT("INSERT", "Insere novos registros em uma tabela."),
    UPDATE("UPDATE", "Atualiza os valores de registros existentes em uma tabela."),
    DELETE("DELETE", "Exclui registros de uma tabela."),
    VALUES("VALUES", "Especifica os valores a serem inseridos ou comparados em um comando."),
    JOIN("JOIN", "Combina registros de duas ou mais tabelas com base em uma coluna comum."),
    LEFT("LEFT", "Junção externa à esquerda (preserva todas as linhas da tabela esquerda)."),
    RIGHT("RIGHT", "Junção externa à direita (preserva todas as linhas da tabela direita)."),
    INNER("INNER", "Junção interna (retorna apenas linhas com correspondência em ambas as tabelas)."),
    OUTER("OUTER", "Especifica uma junção externa (pode ser combinada com LEFT, RIGHT ou FULL)."),
    CROSS("CROSS", "Realiza um produto cartesiano entre duas tabelas (combina todas as linhas)."),
    NATURAL("NATURAL", "Realiza uma junção automática com base em colunas de mesmo nome em ambas as tabelas."),
    FULL("FULL", "Realiza uma junção externa completa (preserva todas as linhas de ambas as tabelas)."),
    ON("ON", "Define a condição de junção entre tabelas em uma cláusula JOIN."),
    AS("AS", "Define um apelido (alias) para uma tabela, coluna ou expressão."),
    UNION("UNION", "Combina o resultado de duas ou mais consultas em um único conjunto de resultados (sem duplicados)."),
    INTERSECT("INTERSECT", "Retorna apenas as linhas que são comuns a ambas as consultas."),
    EXCEPT("EXCEPT", "Retorna as linhas da primeira consulta que não existem na segunda consulta."),
    ALL("ALL", "Retorna todos os registros, incluindo duplicadas, ou compara com todos os valores de uma subconsulta."),
    ANY("ANY", "Compara um valor com qualquer valor retornado por uma subconsulta ou contido em um array."),
    SOME("SOME", "Compara um valor com algum valor de uma subconsulta (sinônimo de ANY)."),
    EXISTS("EXISTS", "Verifica se uma subconsulta retorna qualquer linha de dados."),
    LIKE("LIKE", "Compara valores textuais usando caracteres curinga simples (% e _)."),
    ILIKE("ILIKE", "Compara valores textuais de forma insensível a maiúsculas/minúsculas (exclusivo do PostgreSQL)."),
    IS("IS", "Utilizado em conjunto com NULL ou TRUE/FALSE para testar condições de estado."),
    NULL("NULL", "Representa a ausência de valor ou um valor desconhecido."),
    TRUE("TRUE", "Representa o valor lógico verdadeiro."),
    FALSE("FALSE", "Representa o valor lógico falso."),
    AND("AND", "Operador lógico E (todas as condições devem ser verdadeiras)."),
    OR("OR", "Operador lógico OU (pelo menos uma condição deve ser verdadeira)."),
    NOT("NOT", "Operador lógico de negação."),
    IN("IN", "Verifica se um valor coincide com qualquer valor presente em uma lista ou subconsulta."),
    INTO("INTO", "Direciona o resultado de uma consulta para variáveis locais ou cria uma nova tabela."),
    GROUP("GROUP", "Agrupa linhas que têm os mesmos valores em colunas especificadas (usado com BY)."),
    BY("BY", "Especifica as colunas para agrupamento (GROUP BY) ou ordenação (ORDER BY)."),
    ORDER("ORDER", "Ordena o conjunto de resultados de uma consulta (usado com BY)."),
    LIMIT("LIMIT", "Limita o número máximo de linhas retornadas por uma consulta."),
    OFFSET("OFFSET", "Pula um número especificado de linhas antes de começar a retornar os resultados."),
    HAVING("HAVING", "Filtra os grupos resultantes de uma cláusula GROUP BY com base em condições agregadas."),
    WITH("WITH", "Define expressões de tabela comuns (CTEs) ou opções de tabela."),
    RECURSIVE("RECURSIVE", "Permite que uma CTE faça referência a si mesma para consultas recursivas."),
    DISTINCT("DISTINCT", "Remove linhas duplicadas do resultado de uma consulta."),
    BETWEEN("BETWEEN", "Filtra valores dentro de um intervalo inclusivo de limites inferior e superior."),
    CASE("CASE", "Inicia uma estrutura condicional de escolha (semelhante ao IF-THEN-ELSE no SQL)."),
    WHEN("WHEN", "Especifica a condição a ser testada em uma estrutura CASE ou em definições de TRIGGER."),
    THEN("THEN", "Define a ação ou resultado quando a condição WHEN é considerada verdadeira."),
    ELSE("ELSE", "Define a ação ou resultado padrão quando nenhuma condição condicional anterior é atendida."),
    RETURNING("RETURNING", "Retorna linhas inseridas, atualizadas ou excluídas diretamente pelo comando DML."),
    WINDOW("WINDOW", "Define uma janela de agrupamento móvel para funções analíticas (Window Functions)."),
    OVER("OVER", "Especifica a janela de divisão de dados sobre a qual uma função analítica é calculada."),
    PARTITION("PARTITION", "Divide o conjunto de dados em partições para análise (usado com OVER)."),

    // ==========================================
    // 2. COMANDOS DDL E OBJETOS DO BANCO
    // ==========================================
    CREATE("CREATE", "Cria um novo objeto no banco de dados (tabela, função, trigger, índice, etc.)."),
    DROP("DROP", "Remove permanentemente um objeto do banco de dados."),
    ALTER("ALTER", "Modifica a estrutura de um objeto existente no banco de dados."),
    TABLE("TABLE", "Representa um objeto de tabela física no banco de dados."),
    VIEW("VIEW", "Representa uma consulta armazenada representada como uma tabela virtual."),
    MATERIALIZED("MATERIALIZED", "Define uma View Materializada, que armazena fisicamente o resultado de uma consulta."),
    REFRESH("REFRESH", "Atualiza os dados armazenados em uma View Materializada."),
    FUNCTION("FUNCTION", "Representa uma sub-rotina ou função armazenada no banco de dados."),
    PROCEDURE("PROCEDURE", "Representa um procedimento armazenado (Stored Procedure) que aceita transações."),
    TRIGGER("TRIGGER", "Representa um gatilho disparado automaticamente por eventos de DML."),
    INDEX("INDEX", "Cria ou representa um índice físico para acelerar a busca de dados."),
    INDEXES("INDEXES", "Representa ou refere-se a múltiplos índices de tabelas."),
    SEQUENCE("SEQUENCE", "Cria ou representa um gerador de sequência numérica de autoincremento."),
    SCHEMA("SCHEMA", "Cria ou representa um namespace/esquema isolador dentro de um banco."),
    DATABASE("DATABASE", "Representa a estrutura de um banco de dados no PostgreSQL."),
    DOMAIN("DOMAIN", "Cria um tipo de dado personalizado com restrições e validações."),
    TYPE("TYPE", "Cria um tipo de dado composto, enum ou alias personalizado no banco."),
    CAST("CAST", "Converte explicitamente uma expressão de um tipo de dados para outro."),
    REPLACE("REPLACE", "Substitui um objeto existente se ele já existir (usado com CREATE OR)."),
    ADD("ADD", "Adiciona uma nova coluna ou restrição a uma tabela (usado com ALTER TABLE)."),
    COLUMN("COLUMN", "Especifica uma coluna de tabela em comandos ALTER TABLE."),
    TO("TO", "Especifica o destino ou novo nome em comandos ALTER, RENAME ou GRANT."),
    COMMENT("COMMENT", "Adiciona comentários e documenta objetos (tabelas, colunas, etc.) no dicionário de dados."),
    CONSTRAINT("CONSTRAINT", "Define uma restrição de integridade (PK, FK, etc.) em uma tabela."),
    PRIMARY("PRIMARY", "Define uma chave primária identificadora (usado com KEY)."),
    KEY("KEY", "Define uma chave de integridade (usado com PRIMARY ou FOREIGN)."),
    FOREIGN("FOREIGN", "Define uma chave estrangeira para relacionamento referencial (usado com KEY)."),
    REFERENCES("REFERENCES", "Especifica a tabela e coluna de destino de uma restrição FOREIGN KEY."),
    UNIQUE("UNIQUE", "Garante que todos os valores em uma coluna ou conjunto de colunas sejam distintos."),
    CHECK("CHECK", "Garante que todos os valores em uma coluna atendam a uma restrição lógica definida."),
    DEFAULT("DEFAULT", "Define um valor padrão para uma coluna quando nenhum valor é fornecido."),
    CASCADE("CASCADE", "Propaga a remoção ou atualização automaticamente para objetos dependentes."),
    RESTRICT("RESTRICT", "Impede a remoção ou alteração de objetos se houver outros dependendo deles."),
    RENAME("RENAME", "Altera o nome de um objeto existente (tabela, coluna, etc.)."),
    OWNER("OWNER", "Define ou altera o usuário proprietário de um objeto do banco de dados."),
    SET("SET", "Define valores de configuração da sessão ou atualiza colunas (no UPDATE)."),
    GRANT("GRANT", "Concede privilégios de acesso a objetos para usuários ou funções do banco."),
    REVOKE("REVOKE", "Revoga privilégios de acesso concedidos anteriormente."),
    INHERITS("INHERITS", "Cria uma tabela que herda colunas e propriedades de uma tabela pai."),

    // ==========================================
    // 3. ESTRUTURA E CONTROLE PL/pgSQL
    // ==========================================
    DECLARE("DECLARE", "Inicia a seção de declaração de variáveis locais em blocos PL/pgSQL."),
    BEGIN("BEGIN", "Inicia o bloco de instruções e comandos de execução ativa em PL/pgSQL."),
    END("END", "Finaliza um bloco de instruções ou uma estrutura CASE/BEGIN em PL/pgSQL."),
    IF("IF", "Inicia uma estrutura condicional de decisão lógica em PL/pgSQL."),
    ELSIF("ELSIF", "Introduz uma condição alternativa em uma estrutura condicional IF ativa."),
    LOOP("LOOP", "Inicia um bloco de repetição (laço) infinito/incondicional em PL/pgSQL."),
    WHILE("WHILE", "Inicia um laço de repetição baseado em uma condição verdadeira em PL/pgSQL."),
    FOR("FOR", "Inicia um laço de repetição iterativo (com contadores ou cursores) em PL/pgSQL."),
    FOREACH("FOREACH", "Inicia um laço de repetição que itera sobre elementos de um array em PL/pgSQL."),
    CONTINUE("CONTINUE", "Pula imediatamente para a próxima iteração do laço ativo em PL/pgSQL."),
    EXIT("EXIT", "Termina imediatamente a execução do laço ativo em PL/pgSQL."),
    RETURN("RETURN", "Retorna o controle e opcionalmente um valor de uma função em PL/pgSQL."),
    RETURNS("RETURNS", "Especifica o tipo de dados retornado por uma função em comandos CREATE FUNCTION."),
    LANGUAGE("LANGUAGE", "Especifica a linguagem de programação de uma função (ex: plpgsql)."),
    EXECUTE("EXECUTE", "Executa uma string de comando SQL dinâmica em PL/pgSQL."),
    PERFORM("PERFORM", "Executa uma consulta SQL e descarta o resultado (geralmente usada para funções)."),
    USING("USING", "Passa parâmetros para uma consulta dinâmica executada via EXECUTE."),
    RAISE("RAISE", "Gera uma mensagem de log ou erro estruturado em PL/pgSQL."),
    NOTICE("NOTICE", "Nível de severidade informativa em mensagens RAISE."),
    WARNING("WARNING", "Nível de severidade de alerta em mensagens RAISE."),
    EXCEPTION("EXCEPTION", "Inicia a seção de tratamento de erros ou representa um tipo de erro."),
    CALL("CALL", "Executa um procedimento armazenado (STORED PROCEDURE)."),
    GET("GET", "Obtém informações de diagnóstico da execução (usado com DIAGNOSTICS)."),
    DIAGNOSTICS("DIAGNOSTICS", "Armazena metadados de execução e resultados de DML anteriores."),
    OPEN("OPEN", "Abre um cursor para ler o resultado de uma consulta."),
    CLOSE("CLOSE", "Fecha um cursor aberto."),
    FETCH("FETCH", "Recupera a próxima linha de um cursor aberto."),
    CURSOR("CURSOR", "Declara ou representa um cursor de consulta."),
    CONSTANT("CONSTANT", "Declara que o valor de uma variável local não pode ser alterado após inicializado."),
    STRICT("STRICT", "Garante que a consulta retorne exatamente uma linha, lançando erro caso contrário."),
    ROWTYPE("ROWTYPE", "Representa o tipo de dados correspondente a uma linha inteira de uma tabela."),
    ASSERT("ASSERT", "Avalia uma expressão lógica e lança um erro caso o resultado seja falso."),
    NEXT("NEXT", "Avança o cursor para a próxima linha."),
    PRIOR("PRIOR", "Retrocede o cursor para a linha anterior."),
    FIRST("FIRST", "Posiciona o cursor e lê a primeira linha de dados."),
    LAST("LAST", "Posiciona o cursor e lê a última linha de dados."),
    ABSOLUTE("ABSOLUTE", "Posiciona o cursor em uma linha específica pelo índice absoluto."),
    RELATIVE("RELATIVE", "Posiciona o cursor em uma linha relativa à posição atual."),
    FORWARD("FORWARD", "Move o cursor para frente por um número de linhas."),
    BACKWARD("BACKWARD", "Move o cursor para trás por um número de linhas."),
    SCROLL("SCROLL", "Permite que o cursor seja navegado em qualquer direção (para trás e para frente)."),
    NO("NO", "Parte de modificadores, como NO SCROLL (impede navegação reversa no cursor)."),
    MOVE("MOVE", "Reposiciona um cursor sem recuperar os dados da linha."),

    // ==========================================
    // 4. TRIGGERS E VARIÁVEIS ESPECIAIS
    // ==========================================
    BEFORE("BEFORE", "Especifica que o gatilho (trigger) deve rodar antes do evento DML."),
    AFTER("AFTER", "Especifica que o gatilho (trigger) deve rodar após o evento DML."),
    INSTEAD("INSTEAD", "Especifica que o gatilho deve rodar no lugar do evento de DML (usado com VIEWS)."),
    ROW("ROW", "Define que o gatilho dispara para cada linha afetada (usado com EACH)."),
    EACH("EACH", "Parte da definição de escopo do gatilho (EACH ROW ou EACH STATEMENT)."),
    STATEMENT("STATEMENT", "Define que o gatilho dispara uma vez por comando SQL inteiro."),
    SECURITY("SECURITY", "Define o contexto de privilégios de execução de uma função (usado com DEFINER/INVOKER)."),
    DEFINER("DEFINER", "Executa a função com os privilégios do usuário que a criou."),
    INVOKER("INVOKER", "Executa a função com os privilégios do usuário que a chama (padrão)."),
    COST("COST", "Define o custo estimado de execução de uma função para o otimizador do banco."),
    VOLATILE("VOLATILE", "Informa que o resultado da função pode mudar mesmo com os mesmos argumentos."),
    LEAKPROOF("LEAKPROOF", "Informa que a função não revela informações internas por meio de mensagens de erro."),
    IMMUTABLE("IMMUTABLE", "Informa que a função sempre retorna o mesmo resultado para os mesmos argumentos."),
    STABLE("STABLE", "Informa que a função não modifica o banco e retorna o mesmo resultado dentro de uma transação."),
    CALLED("CALLED", "Parte de CALLED ON NULL INPUT (executa a função mesmo se houver parâmetros nulos)."),
    INPUT("INPUT", "Parte de especificações de entrada de funções."),
    TG_OP("TG_OP", "Variável especial com a operação do trigger (INSERT, UPDATE, DELETE, TRUNCATE)."),
    TG_TABLE_NAME("TG_TABLE_NAME", "Variável especial do trigger que contém o nome da tabela que o disparou."),
    TG_TABLE_SCHEMA("TG_TABLE_SCHEMA", "Variável especial do trigger que contém o esquema da tabela do trigger."),
    TG_NAME("TG_NAME", "Variável especial do trigger que contém o nome do trigger disparado."),
    TG_WHEN("TG_WHEN", "Variável especial do trigger que indica a cláusula WHEN avaliada."),
    TG_LEVEL("TG_LEVEL", "Variável especial do trigger com o nível de escopo (ROW ou STATEMENT)."),
    TG_ARGV("TG_ARGV", "Array com os argumentos textuais passados na definição do trigger."),
    TG_NARGS("TG_NARGS", "Número de argumentos textuais passados na definição do trigger."),
    OLD("OLD", "Variável especial que armazena a linha antiga da tabela em gatilhos de UPDATE/DELETE."),
    NEW("NEW", "Variável especial que armazena a nova linha da tabela em gatilhos de INSERT/UPDATE."),
    FOUND("FOUND", "Variável booleana especial que indica se o último comando DML ou cursor obteve sucesso."),

    // ==========================================
    // 5. PRINCIPAIS TIPOS DE DADOS
    // ==========================================
    INT("INT", "Tipo de dado numérico inteiro de 4 bytes."),
    INTEGER("INTEGER", "Tipo de dado numérico inteiro de 4 bytes (sinônimo de INT)."),
    BIGINT("BIGINT", "Tipo de dado numérico inteiro de 8 bytes para números grandes."),
    SMALLINT("SMALLINT", "Tipo de dado numérico inteiro curto de 2 bytes."),
    NUMERIC("NUMERIC", "Tipo de dado numérico exato com precisão e escala configuráveis."),
    DECIMAL("DECIMAL", "Tipo de dado numérico exato (sinônimo de NUMERIC)."),
    REAL("REAL", "Tipo de dado numérico de ponto flutuante de precisão simples (4 bytes)."),
    DOUBLE("DOUBLE", "Tipo de dado numérico de ponto flutuante de precisão dupla (usado com PRECISION)."),
    PRECISION("PRECISION", "Parte da especificação de tipo DOUBLE PRECISION."),
    VARCHAR("VARCHAR", "Tipo de dado de texto de tamanho variável limitado."),
    CHAR("CHAR", "Tipo de dado de caractere único ou texto de tamanho fixo."),
    CHARACTER("CHARACTER", "Tipo de dado de caractere de tamanho fixo ou variável."),
    TEXT("TEXT", "Tipo de dado textual de tamanho ilimitado."),
    BOOLEAN("BOOLEAN", "Tipo de dado lógico booleano (true/false)."),
    BOOL("BOOL", "Tipo de dado lógico (sinônimo de BOOLEAN)."),
    DATE("DATE", "Tipo de dado de data (ano, mês, dia)."),
    TIME("TIME", "Tipo de dado de hora do dia (sem fuso horário)."),
    TIMESTAMP("TIMESTAMP", "Tipo de dado de data e hora completo (sem fuso horário)."),
    TIMESTAMPTZ("TIMESTAMPTZ", "Tipo de dado de data e hora completo com fuso horário."),
    INTERVAL("INTERVAL", "Tipo de dado representando intervalos ou períodos de tempo."),
    RECORD("RECORD", "Tipo de dado dinâmico representando uma tupla/linha genérica."),
    UUID("UUID", "Tipo de dado para identificador único universal (UUID)."),
    JSON("JSON", "Tipo de dado de texto contendo dados formatados em JSON."),
    JSONB("JSONB", "Tipo de dado binário otimizado para dados em formato JSON."),
    BYTEA("BYTEA", "Tipo de dado para armazenamento de dados binários brutos (byte array)."),
    SERIAL("SERIAL", "Tipo numérico sequencial automático de 4 bytes."),
    BIGSERIAL("BIGSERIAL", "Tipo numérico sequencial automático de 8 bytes."),
    MONEY("MONEY", "Tipo de dado monetário com precisão fixa."),
    XML("XML", "Tipo de dado para armazenamento de dados XML válidos."),
    OID("OID", "Identificador de objeto interno do PostgreSQL."),
    REGCLASS("REGCLASS", "Tipo de dados para referenciar o identificador numérico de uma classe/tabela."),
    CIDR("CIDR", "Tipo de dado para redes IP de versão 4 e 6."),
    INET("INET", "Tipo de dado para endereços IP de hosts e redes."),
    MACADDR("MACADDR", "Tipo de dado para endereços de placas de rede MAC."),
    BIT("BIT", "Tipo de dados para strings de bits de tamanho fixo."),
    VARBIT("VARBIT", "Tipo de dados para strings de bits de tamanho variável."),
    TSVECTOR("TSVECTOR", "Tipo otimizado para busca textual (documento de palavras-chave)."),
    TSQUERY("TSQUERY", "Tipo contendo termos de pesquisa lexical para busca textual."),
    VOID("VOID", "Indica que uma função não retorna um valor útil."),

    // ==========================================
    // 6. OPERADORES E FUNÇÕES AGREGADORAS
    // ==========================================
    MAX("MAX", "Função agregadora que retorna o valor máximo de um conjunto de valores."),
    MIN("MIN", "Função agregadora que retorna o valor mínimo de um conjunto de valores."),
    COUNT("COUNT", "Função agregadora que conta a quantidade de registros retornados."),
    SUM("SUM", "Função agregadora que calcula a soma total de um conjunto numérico."),
    AVG("AVG", "Função agregadora que calcula a média aritmética de um conjunto numérico."),
    STRING_AGG("STRING_AGG", "Concatena valores de string de uma coluna separando-os por um delimitador."),
    ARRAY_AGG("ARRAY_AGG", "Agrupa os valores de entrada em um array do Java/PostgreSQL."),
    JSON_AGG("JSON_AGG", "Agrupa os valores de entrada como uma única matriz JSON."),
    JSONB_AGG("JSONB_AGG", "Agrupa os valores de entrada como uma matriz JSON binária."),
    JSON_OBJECT_AGG("JSON_OBJECT_AGG", "Agrupa pares de chave-valor em um objeto JSON."),
    JSONB_OBJECT_AGG("JSONB_OBJECT_AGG", "Agrupa pares de chave-valor em um objeto JSON binário."),

    // ==========================================
    // 7. FUNÇÕES NATIVAS (BUILT-IN FUNCTIONS)
    // ==========================================
    // --- Manipulação de Strings ---
    UPPER("UPPER", "Converte todos os caracteres de um texto para maiúsculas."),
    LOWER("LOWER", "Converte todos os caracteres de um texto para minúsculas."),
    SUBSTRING("SUBSTRING", "Extrai uma parte (subcadeia) de um texto com base em posições."),
    COALESCE("COALESCE", "Retorna o primeiro valor não nulo da lista de argumentos fornecida."),
    CONCAT("CONCAT", "Concatena os valores de texto de todos os argumentos passados."),
    LENGTH("LENGTH", "Retorna o número de caracteres de um texto."),
    TRIM("TRIM", "Remove espaços em branco do início e do final de um texto."),
    LTRIM("LTRIM", "Remove espaços em branco do início de um texto."),
    RTRIM("RTRIM", "Remove espaços em branco do final de um texto."),
    INITCAP("INITCAP", "Converte a primeira letra de cada palavra em maiúscula e as demais em minúscula."),
    MD5("MD5", "Calcula o hash MD5 de uma string e retorna em formato hexadecimal."),
    SPLIT_PART("SPLIT_PART", "Divide uma string por um delimitador e retorna o campo na posição solicitada."),
    REGEXP_REPLACE("REGEXP_REPLACE", "Substitui substrings que combinam com uma expressão regular por um novo texto."),
    REGEXP_MATCH("REGEXP_MATCH", "Busca correspondências de uma expressão regular em uma string e retorna em array."),
    POSITION("POSITION", "Retorna a posição de início de uma substring dentro de um texto."),
    REVERSE("REVERSE", "Retorna a string com a ordem dos caracteres invertida."),
    TRANSLATE("TRANSLATE", "Substitui caracteres específicos de um texto por caracteres equivalentes de destino."),
    LPAD("LPAD", "Preenche a string à esquerda com um caractere até atingir o comprimento especificado."),
    RPAD("RPAD", "Preenche a string à direita com um caractere até atingir o comprimento especificado."),
    REPEAT("REPEAT", "Repete uma string um número especificado de vezes."),

    // --- Data e Hora ---
    NOW("NOW", "Retorna a data e hora atual do início da transação ativa."),
    CURRENT_DATE("CURRENT_DATE", "Retorna a data atual do sistema."),
    CURRENT_TIME("CURRENT_TIME", "Retorna a hora atual do sistema."),
    CURRENT_TIMESTAMP("CURRENT_TIMESTAMP", "Retorna a data e hora atual completa com fuso horário."),
    LOCALTIME("LOCALTIME", "Retorna a hora local atual do sistema."),
    LOCALTIMESTAMP("LOCALTIMESTAMP", "Retorna a data e hora local atual do sistema."),
    AGE("AGE", "Calcula o intervalo de tempo decorrido entre duas datas (idade)."),
    DATE_PART("DATE_PART", "Extrai uma parte específica de uma data (ano, mês, hora) retornando tipo double."),
    DATE_TRUNC("DATE_TRUNC", "Trunca um timestamp para uma precisão específica (ex: zerar minutos e segundos)."),
    EXTRACT("EXTRACT", "Extrai uma parte específica (ano, mês, dia) de uma data."),
    TO_CHAR("TO_CHAR", "Converte data, hora ou número para uma String formatada."),
    TO_DATE("TO_DATE", "Converte uma String para um tipo DATE usando uma máscara de formatação."),
    TO_NUMBER("TO_NUMBER", "Converte uma String para um tipo NUMERIC usando uma máscara de formatação."),
    TO_TIMESTAMP("TO_TIMESTAMP", "Converte uma String para um tipo TIMESTAMP com fuso horário."),
    CLOCK_TIMESTAMP("CLOCK_TIMESTAMP", "Retorna a data e hora atual real no momento exato da chamada (muda no mesmo comando)."),
    STATEMENT_TIMESTAMP("STATEMENT_TIMESTAMP", "Retorna a data e hora do início da execução da instrução atual."),

    // --- Matemática ---
    ROUND("ROUND", "Arredonda um número para o número mais próximo de casas decimais."),
    TRUNC("TRUNC", "Trunca um número descartando as casas decimais sem realizar arredondamento."),
    ABS("ABS", "Retorna o valor absoluto (positivo) de um número."),
    CEIL("CEIL", "Arredonda um número para cima para o inteiro mais próximo."),
    CEILING("CEILING", "Arredonda um número para cima (sinônimo de CEIL)."),
    FLOOR("FLOOR", "Arredonda um número para baixo para o inteiro mais próximo."),
    MOD("MOD", "Calcula o resto da divisão inteira de dois números."),
    POW("POW", "Calcula a potência de um número elevado a um expoente."),
    POWER("POWER", "Calcula a potência (sinônimo de POW)."),
    SQRT("SQRT", "Calcula a raiz quadrada de um número."),
    DIV("DIV", "Realiza a divisão inteira de dois números."),
    EXP("EXP", "Calcula o valor exponencial (e elevado à potência)."),
    LN("LN", "Calcula o logaritmo natural de um número."),
    LOG("LOG", "Calcula o logaritmo de um número na base especificada."),
    PI("PI", "Retorna o valor constante da constante matemática PI."),
    RANDOM("RANDOM", "Gera um número randômico de ponto flutuante entre 0.0 e 1.0."),
    SIGN("SIGN", "Retorna o sinal de um número (-1 se negativo, 0 se zero, 1 se positivo)."),
    GREATEST("GREATEST", "Retorna o maior valor de uma lista de expressões/argumentos."),
    LEAST("LEAST", "Retorna o menor valor de uma lista de expressões/argumentos."),
    NULLIF("NULLIF", "Retorna nulo se os dois argumentos passados forem iguais."),

    // --- Criptografia e UUID ---
    GEN_RANDOM_UUID("GEN_RANDOM_UUID", "Gera de forma segura um identificador único universal (UUID) randômico."),
    UUID_GENERATE_V4("UUID_GENERATE_V4", "Gera um UUID versão 4 (requer extensão uuid-ossp ativa)."),

    // --- Métodos do Sistema e Utilitários ---
    PG_TRIGGER_DEPTH("pg_trigger_depth", "Retorna o nível de aninhamento atual da execução de gatilhos (triggers)."),
    PG_SLEEP("pg_sleep", "Pausa a execução do processo por um número especificado de segundos."),
    PG_RELOAD_CONF("pg_reload_conf", "Recarrega os arquivos de configuração do servidor de banco de dados."),
    PG_SIZE_PRETTY("pg_size_pretty", "Formata um tamanho em bytes para leitura humana (ex: 10 MB)."),
    PG_RELATION_SIZE("pg_relation_size", "Retorna o tamanho em bytes de uma tabela ou índice."),
    PG_TOTAL_RELATION_SIZE("pg_total_relation_size", "Retorna o tamanho total da tabela incluindo índices e dados TOAST."),
    PG_DATABASE_SIZE("pg_database_size", "Retorna o tamanho total em bytes do banco de dados especificado."),
    CURRENT_SETTING("current_setting", "Obtém o valor atual de um parâmetro de configuração do servidor."),
    SET_CONFIG("set_config", "Define o valor de um parâmetro de configuração do servidor na sessão."),
    SESSION_USER("session_user", "Retorna o nome do usuário que iniciou a sessão atual."),
    CURRENT_USER("current_user", "Retorna o nome do usuário ativo na transação."),
    VERSION("version", "Retorna a string contendo a versão completa do PostgreSQL rodando.");

    private final String palavra;
    private final String descricao;

    PalavraChaveSql(String palavra, String descricao) {
        this.palavra = palavra;
        this.descricao = descricao;
    }

    public String getPalavra() {
        return palavra;
    }

    public String getDescricao() {
        return descricao;
    }

    // Auxiliar para obter a lista de todas as palavras-chave como conjunto de Strings
    public static Set<String> getListaPalavras() {
        return Arrays.stream(values())
                .map(PalavraChaveSql::getPalavra)
                .collect(Collectors.toSet());
    }
}
